name: Flake8
on:
  pull_request: {}
  push: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v3

    - name: set up python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q flake8

    - name: run flake8
      run: flake8
